name: 'Build'

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Linux:   https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/
        qt-version: ['5.13.2', '5.14.2', '5.15.2']
        experimental: [false]
        include:
          - os: ubuntu-latest
            qt-version: '6.1.0'
            experimental: true
    steps:
    - uses: actions/checkout@v2

      #
      # Install Qt
      #
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-${{ matrix.qt-version }}-2
    # https://github.com/marketplace/actions/install-qt
    - if: false == contains( matrix.os, 'windows') && !startsWith( matrix.qt-version, '6.' )
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - if: false == contains( matrix.os, 'windows') && startsWith( matrix.qt-version, '6.' )
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

      #
      # Install enchant-2
      #
    - name: Install enchant-2
      run: |
        git clone https://github.com/AbiWord/enchant
        cd enchant
        ./bootstrap && ./configure --enable-relocatable
        make
        sudo make install

      #
      # Clone dependencys
      #
    - name: Clone MarkdownEdit's dependencys
      run: |
        git submodule update --init --recursive -j 4

      #
      # Build MarkdownEdit
      #
    - name: Build MarkdownEdit
      run: |
        mkdir build && cd build
        qmake ..
        make
