name: 'Build'

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Linux:   https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/
        qt-version: ['5.13.2', '5.14.2', '5.15.2']
        experimental: [false]
    steps:
    - uses: actions/checkout@v2

      #
      # Install Qt
      #

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-${{ matrix.qt-version }}-2
    # https://github.com/marketplace/actions/install-qt
    - if: false == contains( matrix.os, 'windows') && !startsWith( matrix.qt-version, '6.' )
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - if: false == contains( matrix.os, 'windows') && startsWith( matrix.qt-version, '6.' )
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
      #
      # Install enchant-2
      #
    - name: Install enchant-2
      run: |
        wget https://github.com/AbiWord/enchant/releases/download/v2.2.8/enchant-2.2.8.tar.gz
        tar -xf enchant-2.2.8.tar.gz
        cd enchant-2.2.8
        ./configure
        make
        sudo make install
        cd ..
      #
      # Build and install qtspell
      #
    - name: Build QtSpell
      run: |
        git clone https://github.com/software-made-easy/qtspell 3rdparty/qtspell
        mkdir 3rdparty/qtspell/build
        cd 3rdparty/qtspell/build
        cmake ..
        make
        sudo make install
        cd ../../..
      #
      # Install dependencies
      #
    - name: Install MarkdownEdit`s dependencies
      run: |
        git clone https://github.com/mity/md4c 3rdparty/md4c
        git clone https://github.com/Waqar144/QSourceHighlite 3rdparty/QSourceHighlite
        git clone https://github.com/pbek/qmarkdowntextedit 3rdparty/qmarkdowntextedit
      #
      # Build MarkdownEdit
      #
    - name: Build MarkdownEdit
      run: |
        qmake
        make
    - name: make check
      run: make check
